# 地址
#URL: https://live2.kk1397.com/room
URL: http://kx.1396c.com/
#PORT: 8000

# Cookies配置
COOKES:
  - NAME1 : KX_LIVE_TK
    VAULE1: e8524da9b92e4c2b92ebdbc66f76d2ba
  - NAME2 : KX_LIVE_UUID
    VAULE2 : pc-3497046b-59da-4582-8a6f-1d5e1133526b
  - DOMAIN : .1396c.com


# email配置信息
EMAIL:
  - EMAIL_HOST: smtp.qq.com
  - EMAIL_USER: 172667104@qq.com
  - EMAIL_PASSWORD: cigdgjujnyxmbhgd

