# 地址
URL: http://kxlive-web-site.nn711.com/
#PORT: 8000

# Cookies配置
COOKES:
  - NAME1 : KX_LIVE_TK
    VAULE1: ce85202a9a2446809c13ab7dcaafbc6f
  - NAME2 : KX_LIVE_UUID
    VAULE2 : pc-3497046b-59da-4582-8a6f-1d5e1133526b
  - DOMAIN : .nn711.com


# email配置信息
EMAIL:
  - EMAIL_HOST: smtp.qq.com
  - EMAIL_USER: 172667104@qq.com
  - EMAIL_PASSWORD: cigdgjujnyxmbhgd

